### ISSUE TITLE
Android 10 SecurityException

### ISSUE THREAD

**Issue by kgamecarter** [altera2015/usbserial#19]
Google Pixel 2 XL. Android 10
When
`List<UsbDevice> devices = await UsbSerial.listDevices();`

`
E/MethodChannel#usb_serial(25991): Failed to handle method call
E/MethodChannel#usb_serial(25991): java.lang.SecurityException: User has not given 10197/tw.kgame.chameleonminiapp permission to access device /dev/bus/usb/001/002
E/MethodChannel#usb_serial(25991): 	at android.os.Parcel.createException(Parcel.java:2071)
E/MethodChannel#usb_serial(25991): 	at android.os.Parcel.readException(Parcel.java:2039)
E/MethodChannel#usb_serial(25991): 	at android.os.Parcel.readException(Parcel.java:1987)
E/MethodChannel#usb_serial(25991): 	at android.hardware.usb.IUsbSerialReader$Stub$Proxy.getSerial(IUsbSerialReader.java:123)
E/MethodChannel#usb_serial(25991): 	at android.hardware.usb.UsbDevice.getSerialNumber(UsbDevice.java:143)
E/MethodChannel#usb_serial(25991): 	at dev.bessems.usbserial.UsbSerialPlugin.serializeDevice(UsbSerialPlugin.java:205)
E/MethodChannel#usb_serial(25991): 	at dev.bessems.usbserial.UsbSerialPlugin.listDevices(UsbSerialPlugin.java:220)
E/MethodChannel#usb_serial(25991): 	at dev.bessems.usbserial.UsbSerialPlugin.onMethodCall(UsbSerialPlugin.java:258)E/MethodChannel#usb_serial(25991): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#usb_serial(25991): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#usb_serial(25991): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#usb_serial(25991): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#usb_serial(25991): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#usb_serial(25991): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#usb_serial(25991): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#usb_serial(25991): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#usb_serial(25991): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#usb_serial(25991): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/MethodChannel#usb_serial(25991): Caused by: android.os.RemoteException: Remote stack trace:
E/MethodChannel#usb_serial(25991): 	at com.android.server.usb.UsbUserSettingsManager.checkPermission(UsbUserSettingsManager.java:177)
E/MethodChannel#usb_serial(25991): 	at com.android.server.usb.UsbSerialReader.getSerial(UsbSerialReader.java:96)
E/MethodChannel#usb_serial(25991): 	at android.hardware.usb.IUsbSerialReader$Stub.onTransact(IUsbSerialReader.java:84)
E/MethodChannel#usb_serial(25991): 	at android.os.Binder.execTransactInternal(Binder.java:1021)
E/MethodChannel#usb_serial(25991): 	at android.os.Binder.execTransact(Binder.java:994)`

**Comment by kgamecarter** [comment]
Merged
